# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20170329_0650'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date_time'], 'verbose_name': '\u6587\u7ae0\u5217\u8868', 'verbose_name_plural': '\u6587\u7ae0\u5217\u8868'},
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=100, verbose_name='\u540d\u79f0'),
        ),
    ]
