# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 05:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20170405_0546'),
        ('article', '0004_auto_20170405_0541'),
    ]

    operations = [
    ]
