# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-25 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_uploadfileform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfileform',
            name='title',
            field=models.CharField(max_length=50, verbose_name='\u6807\u9898'),
        ),
    ]
