# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-25 05:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20170525_0552'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadfileform',
            options={'verbose_name': '\u6587\u4ef6', 'verbose_name_plural': '\u6587\u4ef6'},
        ),
    ]
