# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-26 03:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20170525_0553'),
        ('article', '0005_merge_20170405_0548'),
    ]

    operations = [
    ]
